---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: volume-snapshot-default-job
  namespace: aap
spec:
  connection_secret: aapaccess
  job_template_name: volume-snapshot
  extra_vars: 
  namespace: default