---
apiVersion: tower.ansible.com/v1alpha1
kind: JobTemplate
metadata:
  name: volume-snapshot-job-template
  namespace: aap
spec:
  tower_auth_secret: aapaccess
  job_template_name: volume-snapshot
  job_template_project: demo-dh
  job_template_ask_vars: true
  job_template_playbook: playbooks/volume-snapshot.yaml
  job_template_inventory: ocp
  job_template_extra_vars:
    namespace: my-app-stage